target_tweet_id: '1824554477870842112'
paths:
  thread_metadata: /Users/luketervit/Desktop/Dissertation_Final/test_3threads/thread_002/thread_metadata.json
  agents_for_thread: /Users/luketervit/Desktop/Dissertation_Final/test_3threads/thread_002/agents_for_thread.csv
abm:
  lurker_ratio: 0
  lurker_dist_strategy: match_active_agents
  bounded_confidence_threshold: 0.3
  backfire_threshold: 0.6
  backfire_aggression_min: 0.7
llm:
  provider: ollama
  model: dolphin-llama3:8b
  api_key_env: null
  temperature: 0.9
  max_tokens: 150
thread_info:
  root_tweet_id: '1824554477870842112'
  internal_replies: 969
  max_depth: 5
  root_text: 'Since Harris took office:


    Car insurance is up 54%

    Hotels are up 51.2%

    Gas is up 50.5%

    Fuel oil is u'
simulation:
  max_rounds: 5
  thread_num: 2
